server:
    port: 8585
jms:
    jwt:
        security:
            enabled: true
        timezone: "America/Ciudad_de_Mexico"
        issuer: "www.vaescode.com"
        token:
            auth:
                path: "/v1.0/oauth/client_credential/accesstoken"
            secret: "Esta es la firma secreta que nadie debe conocer"
            expiration: 3600 #segundos
        excluded:
            path: "/v1.0/multi/v1.0/otra_exclusion" #ruta de la peticion que no requiere autenticacion
