server:
    port: 8585
    error:
        include-stacktrace: never

jms:
    jwt:
        security:
            enabled: true
        timezone: "America/Mexico_City"
        issuer: "www.vaescode.com"
        token:
            auth:
                path: "/v1.0/oauth/client_credential/accesstoken"
            secret: "esta es la frase secreta"
            expires-in: 60 #1H - segundos declaración de expiración de token
        excluded:
            path: "/v1.0/multi/v1.0/otraexclusion"
